/*
 * BlueJeans Meetings REST API
 *  ## Video That Works Where You Do. <p>This site provides developers access to APIs from BlueJean's Meetings meeting service.  From here you can see and try actual API calls to manage User Accounts, Meetings, and Recordings, pull Analytical Data and Current State information.</p>    <nosdk> <hr> <div> <div class=\"key\">     <a href=\"./basics.html\" target=\"_\"><img class=\"keyimg\" src=\"./img/bjnmeeting.png\"/></a> </div> <div class=\"keybox\"> Basic instructions about What is a BlueJeans Meeting, and Getting Started Using API's, are <a href=\"./basics.html\" target=\"_blank\">available here <i class=\"glyphicon glyphicon-new-window\"></i></a>. </div> </div> <hr> <alert>2/21/2019</alert> Change response of Change layout and Endpoint API's to 204<br/> 12/03/2018 Add API for setting user profile photograph.<br/> 10/17/2018 Updated API field definitions for time variables to be 64-bit .<br/> 7/23/2018 Corrected errors in API definition file.<br/> 7/10/2018 Deprecated some Command Center API's.  Exposed API's that Summarize usage.<br/> 7/06/2018 Added API for changing ownership of recordings.<br/> 6/28/2018 Restored Create Enterprise Account, added Enterprise and User Profile Tag API's.<br/> 6/01/2018 Clarified Access Token requirements for meeting endpoint API's.<br/> 5/21/2018 Corrected return model for meeting history call.<br/> </nosdk> <hr> 
 *
 * OpenAPI spec version: 1.0.4402212019
 * Contact: glenn@bluejeans.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bluejeans.api.rest.meetings.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AnalyticsEndpointDistributionDistribution
 */

public class AnalyticsEndpointDistributionDistribution {
  @SerializedName("Google")
  private Integer google = null;

  @SerializedName("Telepresence")
  private Integer telepresence = null;

  @SerializedName("Lync")
  private Integer lync = null;

  @SerializedName("iOS")
  private Integer iOS = null;

  @SerializedName("H323")
  private Integer h323 = null;

  @SerializedName("InterCall")
  private Integer interCall = null;

  @SerializedName("Jabber")
  private Integer jabber = null;

  @SerializedName("Android")
  private Integer android = null;

  @SerializedName("Skype")
  private Integer skype = null;

  @SerializedName("ISDN")
  private Integer ISDN = null;

  @SerializedName("PSTN")
  private Integer PSTN = null;

  @SerializedName("Level3")
  private Integer level3 = null;

  @SerializedName("SIP")
  private Integer SIP = null;

  @SerializedName("BlueJeansApp")
  private Integer blueJeansApp = null;

  @SerializedName("Browser")
  private Integer browser = null;

  @SerializedName("WebRTC")
  private Integer webRTC = null;

  public AnalyticsEndpointDistributionDistribution google(Integer google) {
    this.google = google;
    return this;
  }

   /**
   * Get google
   * @return google
  **/
  @ApiModelProperty(value = "")
  public Integer getGoogle() {
    return google;
  }

  public void setGoogle(Integer google) {
    this.google = google;
  }

  public AnalyticsEndpointDistributionDistribution telepresence(Integer telepresence) {
    this.telepresence = telepresence;
    return this;
  }

   /**
   * Get telepresence
   * @return telepresence
  **/
  @ApiModelProperty(value = "")
  public Integer getTelepresence() {
    return telepresence;
  }

  public void setTelepresence(Integer telepresence) {
    this.telepresence = telepresence;
  }

  public AnalyticsEndpointDistributionDistribution lync(Integer lync) {
    this.lync = lync;
    return this;
  }

   /**
   * Get lync
   * @return lync
  **/
  @ApiModelProperty(value = "")
  public Integer getLync() {
    return lync;
  }

  public void setLync(Integer lync) {
    this.lync = lync;
  }

  public AnalyticsEndpointDistributionDistribution iOS(Integer iOS) {
    this.iOS = iOS;
    return this;
  }

   /**
   * Get iOS
   * @return iOS
  **/
  @ApiModelProperty(value = "")
  public Integer getIOS() {
    return iOS;
  }

  public void setIOS(Integer iOS) {
    this.iOS = iOS;
  }

  public AnalyticsEndpointDistributionDistribution h323(Integer h323) {
    this.h323 = h323;
    return this;
  }

   /**
   * Get h323
   * @return h323
  **/
  @ApiModelProperty(value = "")
  public Integer getH323() {
    return h323;
  }

  public void setH323(Integer h323) {
    this.h323 = h323;
  }

  public AnalyticsEndpointDistributionDistribution interCall(Integer interCall) {
    this.interCall = interCall;
    return this;
  }

   /**
   * Get interCall
   * @return interCall
  **/
  @ApiModelProperty(value = "")
  public Integer getInterCall() {
    return interCall;
  }

  public void setInterCall(Integer interCall) {
    this.interCall = interCall;
  }

  public AnalyticsEndpointDistributionDistribution jabber(Integer jabber) {
    this.jabber = jabber;
    return this;
  }

   /**
   * Get jabber
   * @return jabber
  **/
  @ApiModelProperty(value = "")
  public Integer getJabber() {
    return jabber;
  }

  public void setJabber(Integer jabber) {
    this.jabber = jabber;
  }

  public AnalyticsEndpointDistributionDistribution android(Integer android) {
    this.android = android;
    return this;
  }

   /**
   * Get android
   * @return android
  **/
  @ApiModelProperty(value = "")
  public Integer getAndroid() {
    return android;
  }

  public void setAndroid(Integer android) {
    this.android = android;
  }

  public AnalyticsEndpointDistributionDistribution skype(Integer skype) {
    this.skype = skype;
    return this;
  }

   /**
   * Get skype
   * @return skype
  **/
  @ApiModelProperty(value = "")
  public Integer getSkype() {
    return skype;
  }

  public void setSkype(Integer skype) {
    this.skype = skype;
  }

  public AnalyticsEndpointDistributionDistribution ISDN(Integer ISDN) {
    this.ISDN = ISDN;
    return this;
  }

   /**
   * Get ISDN
   * @return ISDN
  **/
  @ApiModelProperty(value = "")
  public Integer getISDN() {
    return ISDN;
  }

  public void setISDN(Integer ISDN) {
    this.ISDN = ISDN;
  }

  public AnalyticsEndpointDistributionDistribution PSTN(Integer PSTN) {
    this.PSTN = PSTN;
    return this;
  }

   /**
   * Get PSTN
   * @return PSTN
  **/
  @ApiModelProperty(value = "")
  public Integer getPSTN() {
    return PSTN;
  }

  public void setPSTN(Integer PSTN) {
    this.PSTN = PSTN;
  }

  public AnalyticsEndpointDistributionDistribution level3(Integer level3) {
    this.level3 = level3;
    return this;
  }

   /**
   * Get level3
   * @return level3
  **/
  @ApiModelProperty(value = "")
  public Integer getLevel3() {
    return level3;
  }

  public void setLevel3(Integer level3) {
    this.level3 = level3;
  }

  public AnalyticsEndpointDistributionDistribution SIP(Integer SIP) {
    this.SIP = SIP;
    return this;
  }

   /**
   * Get SIP
   * @return SIP
  **/
  @ApiModelProperty(value = "")
  public Integer getSIP() {
    return SIP;
  }

  public void setSIP(Integer SIP) {
    this.SIP = SIP;
  }

  public AnalyticsEndpointDistributionDistribution blueJeansApp(Integer blueJeansApp) {
    this.blueJeansApp = blueJeansApp;
    return this;
  }

   /**
   * Get blueJeansApp
   * @return blueJeansApp
  **/
  @ApiModelProperty(value = "")
  public Integer getBlueJeansApp() {
    return blueJeansApp;
  }

  public void setBlueJeansApp(Integer blueJeansApp) {
    this.blueJeansApp = blueJeansApp;
  }

  public AnalyticsEndpointDistributionDistribution browser(Integer browser) {
    this.browser = browser;
    return this;
  }

   /**
   * Get browser
   * @return browser
  **/
  @ApiModelProperty(value = "")
  public Integer getBrowser() {
    return browser;
  }

  public void setBrowser(Integer browser) {
    this.browser = browser;
  }

  public AnalyticsEndpointDistributionDistribution webRTC(Integer webRTC) {
    this.webRTC = webRTC;
    return this;
  }

   /**
   * Get webRTC
   * @return webRTC
  **/
  @ApiModelProperty(value = "")
  public Integer getWebRTC() {
    return webRTC;
  }

  public void setWebRTC(Integer webRTC) {
    this.webRTC = webRTC;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalyticsEndpointDistributionDistribution analyticsEndpointDistributionDistribution = (AnalyticsEndpointDistributionDistribution) o;
    return Objects.equals(this.google, analyticsEndpointDistributionDistribution.google) &&
        Objects.equals(this.telepresence, analyticsEndpointDistributionDistribution.telepresence) &&
        Objects.equals(this.lync, analyticsEndpointDistributionDistribution.lync) &&
        Objects.equals(this.iOS, analyticsEndpointDistributionDistribution.iOS) &&
        Objects.equals(this.h323, analyticsEndpointDistributionDistribution.h323) &&
        Objects.equals(this.interCall, analyticsEndpointDistributionDistribution.interCall) &&
        Objects.equals(this.jabber, analyticsEndpointDistributionDistribution.jabber) &&
        Objects.equals(this.android, analyticsEndpointDistributionDistribution.android) &&
        Objects.equals(this.skype, analyticsEndpointDistributionDistribution.skype) &&
        Objects.equals(this.ISDN, analyticsEndpointDistributionDistribution.ISDN) &&
        Objects.equals(this.PSTN, analyticsEndpointDistributionDistribution.PSTN) &&
        Objects.equals(this.level3, analyticsEndpointDistributionDistribution.level3) &&
        Objects.equals(this.SIP, analyticsEndpointDistributionDistribution.SIP) &&
        Objects.equals(this.blueJeansApp, analyticsEndpointDistributionDistribution.blueJeansApp) &&
        Objects.equals(this.browser, analyticsEndpointDistributionDistribution.browser) &&
        Objects.equals(this.webRTC, analyticsEndpointDistributionDistribution.webRTC);
  }

  @Override
  public int hashCode() {
    return Objects.hash(google, telepresence, lync, iOS, h323, interCall, jabber, android, skype, ISDN, PSTN, level3, SIP, blueJeansApp, browser, webRTC);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalyticsEndpointDistributionDistribution {\n");
    
    sb.append("    google: ").append(toIndentedString(google)).append("\n");
    sb.append("    telepresence: ").append(toIndentedString(telepresence)).append("\n");
    sb.append("    lync: ").append(toIndentedString(lync)).append("\n");
    sb.append("    iOS: ").append(toIndentedString(iOS)).append("\n");
    sb.append("    h323: ").append(toIndentedString(h323)).append("\n");
    sb.append("    interCall: ").append(toIndentedString(interCall)).append("\n");
    sb.append("    jabber: ").append(toIndentedString(jabber)).append("\n");
    sb.append("    android: ").append(toIndentedString(android)).append("\n");
    sb.append("    skype: ").append(toIndentedString(skype)).append("\n");
    sb.append("    ISDN: ").append(toIndentedString(ISDN)).append("\n");
    sb.append("    PSTN: ").append(toIndentedString(PSTN)).append("\n");
    sb.append("    level3: ").append(toIndentedString(level3)).append("\n");
    sb.append("    SIP: ").append(toIndentedString(SIP)).append("\n");
    sb.append("    blueJeansApp: ").append(toIndentedString(blueJeansApp)).append("\n");
    sb.append("    browser: ").append(toIndentedString(browser)).append("\n");
    sb.append("    webRTC: ").append(toIndentedString(webRTC)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

