//
// MeetingIndigoList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MeetingIndigoList: Codable {

    public var meetings: [MeetingIndigo]?

    public init(meetings: [MeetingIndigo]?) {
        self.meetings = meetings
    }


}

